**1- Write a Python program to convert an array to an ordinary list with the same items.**

In [ ]:
import numpy as np
A=np.array([[1,2,3],[8,5,4],[7,17,56]])
B=A.tolist()
liste_plate = []
for i in B:
    for j in i:
       liste_plate.append(j)
# Affichage
print("Initial Array:", B)
print("Ordinary List:", liste_plate)

Initial Array: [[1, 2, 3], [8, 5, 4], [7, 17, 56]]
Ordinary List: [1, 2, 3, 8, 5, 4, 7, 17, 56]


**2-Write a NumPy program to compute the sum of the diagonal element of a given array.**

In [ ]:
import numpy as np
A=np.array([[1,2,3],[8,5,4],[7,17,56]])
C=A.diagonal()
somme_diagonale = 0
for i in range(0,len(C)):
  somme_diagonale = somme_diagonale + C[i]
print(somme_diagonale) 

62


**3- Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.**

In [ ]:
import numpy as np                              # Meme code que 1 , je rajoute la partie pour la comparaison des éléments à un X donné
A=np.array([[1,2,3],[8,5,4],[7,17,56]])
B=A.tolist()
liste_plate=[]
for i in B:
    for j in i:
       liste_plate.append(j)                                

list=[]                                     # Définition d'une liste vide qui contiendra les éléments supérieurs à x
x=int(input())
for c in liste_plate:
   if c>x:
      list.append(c)

print(list)


5


[8, 7, 17, 56]

**4- Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array.**

In [ ]:
import numpy as np
A=np.array([[1,2,3,10],[5,8,2,0],[8,8,5,5],[14,2,198,201]])
B=np.array([[8,5,2,1],[8,4,0,2],[8,5,2,9],[8,0,1,5]])
L=len(A)
C=np.empty(shape=(L,L),dtype='object')                      # Initialisation d'une matrice somme de C=A+B "vide"
list_A=[]                                                  
list_B=[]
A=A.tolist()
B=B.tolist()                                                # Conversion des array en listes ici l'idée est de mettre le total sous la forme d'une somme de deux listes
if len(A)==len(B):                                          # controle si les matrices sont sommables
  for i in A:
    for j in i:
              list_A.append(j)                              #rendre la liste "plate"
else:
  print("erreur on peut pas sommer les deux matrice")

for i in B:
    for j in i:
              list_B.append(j)                             #...de même ici pour B

list_C=[]                                                  # list_C = list_A + list_B
for i in range(0,len(list_A),1):                           
    list_C.append(list_A[i]+list_B[i])                     # somme ordinaire des listes élément par élément
sum=np.array(list_C)                                       # conversion liste-->array                                   
sum=sum.reshape(L,L)                                       # un coup de relooking ;)
print(sum)

[[  9   7   5  11]
 [ 13  12   2   2]
 [ 16  13   7  14]
 [ 22   2 199 206]]
